# Generated by Django 2.1.7 on 2019-03-29 04:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('user_id', models.CharField(default='abc', max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('experience', models.IntegerField(blank=True, default=0, null=True)),
                ('current_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('highest_education', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone_number', models.IntegerField(blank=True, default=0, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('website', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('current_company', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='abc', max_length=50)),
                ('qualification', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('percentage', models.IntegerField(default=0)),
                ('institution', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('job_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('job_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=1000)),
                ('job_type', models.CharField(max_length=100)),
                ('job_categories', models.CharField(max_length=100)),
                ('minimum_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('maximum_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('career_level', models.CharField(max_length=100)),
                ('minimum_experience', models.IntegerField(default=0)),
                ('maximum_experience', models.IntegerField(default=0)),
                ('required_gender', models.CharField(max_length=10)),
                ('industry', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('application_deadline', models.DateField(blank=True)),
                ('key_skills', models.CharField(max_length=500)),
                ('secondary_skills', models.CharField(max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='Active', max_length=100)),
                ('total_applied', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('education_detail_desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('skill_detailed_desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='abc', max_length=50)),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_percentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='abc', max_length=50)),
                ('job_title', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('is_present_job', models.BooleanField(default=False, null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('project_details', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='workexperience',
            unique_together={('user_id', 'job_title')},
        ),
        migrations.AlterUniqueTogether(
            name='skillset',
            unique_together={('user_id', 'skill_name')},
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('user_id', 'job_code')},
        ),
        migrations.AlterUniqueTogether(
            name='educationdetails',
            unique_together={('user_id', 'qualification')},
        ),
    ]
