# Generated by Django 2.1.7 on 2019-03-19 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=1000)),
                ('job_type', models.CharField(max_length=100)),
                ('job_categories', models.CharField(max_length=100)),
                ('minimum_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('maximum_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('career_level', models.CharField(max_length=100)),
                ('minimum_experience', models.IntegerField(default=0)),
                ('maximum_experience', models.IntegerField(default=0)),
                ('required_gender', models.CharField(max_length=10)),
                ('industry', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('application_deadline', models.DateField(default=datetime.date.today)),
                ('key_skills', models.CharField(max_length=500)),
                ('created_by', models.CharField(max_length=100)),
                ('creation_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
