# Generated by Django 2.1.7 on 2019-03-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='job_code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
