# Generated by Django 2.1.7 on 2019-03-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190319_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
