# Generated by Django 2.1.7 on 2019-03-19 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190319_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='application_deadline',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
