# Generated by Django 2.1.7 on 2019-03-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190319_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='active',
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='total_applied',
            field=models.IntegerField(default=0),
        ),
    ]
